kube:
  - name: k8s_api_pod
    namespace: dclo-api-ns
    serviceLabel: app=dclo-api
    logPath: /app/logs/app.ndjson
    format: ndjson
  - name: k8s_kv_pod
    namespace: dclo-api-ns
    serviceLabel: app=dclo-key-validation
    logPath: /app/logs/app.log
    format: log
